
style = "full"
command_chaining = true

inline_height_shell_up_key_binding = 5

exit_mode = "return-original"


enter_accept = false



prefers_reduced_motion = true

[stats]


[keys]
# Defaults to true. If disabled, using the up/down key won't exit the TUI when scrolled past the first/last entry.
# scroll_exits = true
# Defaults to true. The left arrow key will exit the TUI when scrolling before the first character
# exit_past_line_start = true
# Defaults to true. The right arrow key performs the same functionality as Tab and copies the selected line to the command line to be modified.
# accept_past_line_end = true

[sync]
records = true

[logs]
dir = "~/.local/share/atuin/logs/"

[daemon]
enabled = false

[theme]
name = "tokyonight"
## Color theme to use for rendering in the terminal.
## There are some built-in themes, including the base theme ("default"),
## "autumn" and "marine". You can add your own themes to the "./themes" subdirectory of your
## Atuin config (or ATUIN_THEME_DIR, if provided) as TOML files whose keys should be one or
## more of AlertInfo, AlertWarn, AlertError, Annotation, Base, Guidance, Important, and
## the string values as lowercase entries from this list:
##    https://ogeon.github.io/docs/palette/master/palette/named/index.html
## If you provide a custom theme file, it should be  called "NAME.toml" and the theme below
## should be the stem, i.e. `theme = "NAME"` for your chosen NAME.
# name = "autumn"

## Whether the theme manager should output normal or extra information to help fix themes.
## Boolean, true or false. If unset, left up to the theme manager.
# debug = true

[search]
filters = [ "global", "host"]

